### ISSUE TITLE
Error with forward slash character in "title"

### ISSUE THREAD

**Issue by piersandro** [BenjaminBrandmeier/google-to-simplenote#1]
Hi and thank you for your useful tool.

I tried to export my 762 notes from Google Keep but I had problem with 9 of these that had errors like the following:

```
NotFound: No such file or directory (os error 2), open 'simplenote_generated/Installare/Rimuovere Desktop a Ubuntu Server.txt'
    at Object.opSync (deno:core/01_core.js:149:12)
    at openSync (deno:runtime/js/40_files.js:37:22)
    at writeFileSync (deno:runtime/js/40_write_file.js:28:18)
    at Object.writeTextFileSync (deno:runtime/js/40_write_file.js:92:12)
    at createSimpleNoteFile (file:///Users/piersandro/tmp/google-to-simplenote/convert.ts:5:74)
    at parseContents (file:///Users/piersandro/tmp/google-to-simplenote/convert.ts:16:13)
    at file:///Users/piersandro/tmp/google-to-simplenote/convert.ts:38:19
    at Array.map (<anonymous>)
    at file:///Users/piersandro/tmp/google-to-simplenote/convert.ts:38:10
unable to convert Installare_Rimuovere Desktop a Ubuntu Server.json
```

The problem is that the "title" of the note contained the forward slash: "Installare/Rimuovere Desktop a Ubuntu Server"

The script worked, it not halted, but ignored notes with "/" in the "title".

Could be nice to convert the the "/" with "_" in the generated files to complete the conversion.

I solved by manually substitute the "/" character in the "title" inside the files with a minus but it was a workaround.

**Comment by BenjaminBrandmeier** [comment]
fixed. thx for raising the issue.
